### PR TITLE
Update modifying-one-to-one-edges.md

### PR DESCRIPTION
**Pull request by fvieira**

### CODE REVIEW

**Comment by marktani** [comment]
Could you adjust the Relay API article similarly, as well? That can be done for all 3 of your recent PRs 🙂

**Comment by fvieira** [comment]
Sure! Will do!

**Comment by fvieira** [comment]
Done

**Comment by marktani** [comment]
Thanks so much, Francisco 🙌

**Comment by marktani** [comment]
I [added you as contributor](https://github.com/graphcool/content/commit/333f085ce42f5dae8af81db7bc59a9d84f07d318) 🙏

**Pull request merged**
