### PR TITLE
Fixed undefined id.

### PR DESCRIPTION
**Pull request by Igor-Senshov**

### CODE REVIEW

**Comment by marktani** [comment]
Hey @Igor-Senshov can you elaborate this suggestion? `node.id` should work using the [Graphcool Relay API](https://www.graph.cool/docs/reference/relay-api/overview-aizoong9ah/).

**Comment by Igor-Senshov** [comment]
Hi, @marktani! It returns `undefined` for me, and React were complaining that each child should have a unique key and was pointing to the ListPage component. I checked and found that `node` has `__id` key.
If you run the app, you should see the warning from React in the console.

**Comment by marktani** [comment]
Thanks @Igor-Senshov 🙁

**Comment by Igor-Senshov** [comment]
Thank you for the tutorial, learned a lot from it! Much better than official.

**Pull request merged**
